project_id = "aonequdtprbhviskbvrw"

[functions.wechat-exchange]
verify_jwt = false

[functions.sms-send]
verify_jwt = false

[functions.sms-verify]
verify_jwt = false

[functions.seed-demo-merchant]
verify_jwt = false
