project_id = "aonequdtprbhviskbvrw"

[functions.wechat-exchange]
verify_jwt = false

[functions.sms-send]
verify_jwt = false

[functions.sms-verify]
verify_jwt = false

[functions.seed-demo-merchant]
verify_jwt = false

[functions.phone-password-login]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.pay-wx-start]
verify_jwt = false

[functions.pay-wx-callback]
verify_jwt = false

[functions.pay-create]
verify_jwt = false

[functions.pay-notify]
verify_jwt = false
