/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PcRouteImport } from './routes/pc'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PcIndexRouteImport } from './routes/pc.index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WalletTransactionsRouteImport } from './routes/wallet_.transactions'
import { Route as ShopMeRouteImport } from './routes/shop.me'
import { Route as ShopMerchantIdRouteImport } from './routes/shop.$merchantId'
import { Route as ProfileKycRouteImport } from './routes/profile_.kyc'
import { Route as ProfileBindPhoneRouteImport } from './routes/profile_.bind-phone'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as PcWalletTransactionsRouteImport } from './routes/pc.wallet-transactions'
import { Route as PcUsersRouteImport } from './routes/pc.users'
import { Route as PcPaymentsRouteImport } from './routes/pc.payments'
import { Route as PcOrdersRouteImport } from './routes/pc.orders'
import { Route as PcLoginRouteImport } from './routes/pc.login'
import { Route as PcCustomersRouteImport } from './routes/pc.customers'
import { Route as PcCommissionsRouteImport } from './routes/pc.commissions'
import { Route as PcAgentsRouteImport } from './routes/pc.agents'
import { Route as PayTestRouteImport } from './routes/pay.test'
import { Route as PaySuccessRouteImport } from './routes/pay.success'
import { Route as OrdersOrderIdRouteImport } from './routes/orders_.$orderId'
import { Route as MerchantShopRouteImport } from './routes/merchant.shop'
import { Route as MerchantQrcodeRouteImport } from './routes/merchant.qrcode'
import { Route as MerchantMessagesRouteImport } from './routes/merchant.messages'
import { Route as MerchantCommissionRouteImport } from './routes/merchant.commission'
import { Route as MerchantApplyRouteImport } from './routes/merchant.apply'
import { Route as MerchantAgentsRouteImport } from './routes/merchant.agents'
import { Route as MerchantAgentRecruitRouteImport } from './routes/merchant.agent-recruit'
import { Route as MerchantAgentApplicationsRouteImport } from './routes/merchant.agent-applications'
import { Route as MerchantAffiliationsRouteImport } from './routes/merchant.affiliations'
import { Route as LoginWechatDoneRouteImport } from './routes/login.wechat-done'
import { Route as LoginIframeBridgeRouteImport } from './routes/login.iframe-bridge'
import { Route as LoginDoneRouteImport } from './routes/login.done'
import { Route as AuthStaffLoginRouteImport } from './routes/auth.staff-login'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApplyAgentMerchantIdRouteImport } from './routes/apply-agent.$merchantId'
import { Route as AgentShareRouteImport } from './routes/agent_.share'
import { Route as AgentMerchantsRouteImport } from './routes/agent_.merchants'
import { Route as AgentInviteesRouteImport } from './routes/agent_.invitees'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminWechatRouteImport } from './routes/admin.wechat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRechargeRouteImport } from './routes/admin.recharge'
import { Route as AdminPaymentLogsRouteImport } from './routes/admin.payment-logs'
import { Route as AdminPaymentRouteImport } from './routes/admin.payment'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminMerchantRecruitRouteImport } from './routes/admin.merchant-recruit'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminCommissionRouteImport } from './routes/admin.commission'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as MerchantProductsIndexRouteImport } from './routes/merchant.products.index'
import { Route as MerchantProductsNewRouteImport } from './routes/merchant.products.new'
import { Route as MerchantAgentsUserIdRouteImport } from './routes/merchant.agents.$userId'
import { Route as ApiPublicPayNotifyRouteImport } from './routes/api/public/pay-notify'
import { Route as PcUsersMerchantMerchantIdRouteImport } from './routes/pc.users_.merchant.$merchantId'
import { Route as PcUsersBuyerUserIdRouteImport } from './routes/pc.users_.buyer.$userId'
import { Route as PcUsersAgentUserIdRouteImport } from './routes/pc.users_.agent.$userId'
import { Route as MerchantProductsProductIdIssuesIndexRouteImport } from './routes/merchant.products.$productId.issues.index'
import { Route as MerchantProductsProductIdIssuesNewRouteImport } from './routes/merchant.products.$productId.issues.new'
import { Route as MerchantProductsProductIdIssuesBulkImportRouteImport } from './routes/merchant.products.$productId.issues.bulk-import'
import { Route as MerchantProductsProductIdIssuesIssueIdEditRouteImport } from './routes/merchant.products.$productId.issues.$issueId.edit'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PcRoute = PcRouteImport.update({
  id: '/pc',
  path: '/pc',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PcIndexRoute = PcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PcRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletTransactionsRoute = WalletTransactionsRouteImport.update({
  id: '/wallet_/transactions',
  path: '/wallet/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMeRoute = ShopMeRouteImport.update({
  id: '/shop/me',
  path: '/shop/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMerchantIdRoute = ShopMerchantIdRouteImport.update({
  id: '/shop/$merchantId',
  path: '/shop/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileKycRoute = ProfileKycRouteImport.update({
  id: '/profile_/kyc',
  path: '/profile/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBindPhoneRoute = ProfileBindPhoneRouteImport.update({
  id: '/profile_/bind-phone',
  path: '/profile/bind-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PcWalletTransactionsRoute = PcWalletTransactionsRouteImport.update({
  id: '/wallet-transactions',
  path: '/wallet-transactions',
  getParentRoute: () => PcRoute,
} as any)
const PcUsersRoute = PcUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PcRoute,
} as any)
const PcPaymentsRoute = PcPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PcRoute,
} as any)
const PcOrdersRoute = PcOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PcRoute,
} as any)
const PcLoginRoute = PcLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PcRoute,
} as any)
const PcCustomersRoute = PcCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PcRoute,
} as any)
const PcCommissionsRoute = PcCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => PcRoute,
} as any)
const PcAgentsRoute = PcAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PcRoute,
} as any)
const PayTestRoute = PayTestRouteImport.update({
  id: '/pay/test',
  path: '/pay/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/pay/success',
  path: '/pay/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantShopRoute = MerchantShopRouteImport.update({
  id: '/merchant/shop',
  path: '/merchant/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantQrcodeRoute = MerchantQrcodeRouteImport.update({
  id: '/merchant/qrcode',
  path: '/merchant/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantMessagesRoute = MerchantMessagesRouteImport.update({
  id: '/merchant/messages',
  path: '/merchant/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantCommissionRoute = MerchantCommissionRouteImport.update({
  id: '/merchant/commission',
  path: '/merchant/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApplyRoute = MerchantApplyRouteImport.update({
  id: '/merchant/apply',
  path: '/merchant/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAgentsRoute = MerchantAgentsRouteImport.update({
  id: '/merchant/agents',
  path: '/merchant/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAgentRecruitRoute = MerchantAgentRecruitRouteImport.update({
  id: '/merchant/agent-recruit',
  path: '/merchant/agent-recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAgentApplicationsRoute =
  MerchantAgentApplicationsRouteImport.update({
    id: '/merchant/agent-applications',
    path: '/merchant/agent-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantAffiliationsRoute = MerchantAffiliationsRouteImport.update({
  id: '/merchant/affiliations',
  path: '/merchant/affiliations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginWechatDoneRoute = LoginWechatDoneRouteImport.update({
  id: '/login/wechat-done',
  path: '/login/wechat-done',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIframeBridgeRoute = LoginIframeBridgeRouteImport.update({
  id: '/login/iframe-bridge',
  path: '/login/iframe-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDoneRoute = LoginDoneRouteImport.update({
  id: '/login/done',
  path: '/login/done',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStaffLoginRoute = AuthStaffLoginRouteImport.update({
  id: '/auth/staff-login',
  path: '/auth/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAgentMerchantIdRoute = ApplyAgentMerchantIdRouteImport.update({
  id: '/apply-agent/$merchantId',
  path: '/apply-agent/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentShareRoute = AgentShareRouteImport.update({
  id: '/agent_/share',
  path: '/agent/share',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMerchantsRoute = AgentMerchantsRouteImport.update({
  id: '/agent_/merchants',
  path: '/agent/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentInviteesRoute = AgentInviteesRouteImport.update({
  id: '/agent_/invitees',
  path: '/agent/invitees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWechatRoute = AdminWechatRouteImport.update({
  id: '/admin/wechat',
  path: '/admin/wechat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRechargeRoute = AdminRechargeRouteImport.update({
  id: '/admin/recharge',
  path: '/admin/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentLogsRoute = AdminPaymentLogsRouteImport.update({
  id: '/admin/payment-logs',
  path: '/admin/payment-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentRoute = AdminPaymentRouteImport.update({
  id: '/admin/payment',
  path: '/admin/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/admin/merchants',
  path: '/admin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantRecruitRoute = AdminMerchantRecruitRouteImport.update({
  id: '/admin/merchant-recruit',
  path: '/admin/merchant-recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionRoute = AdminCommissionRouteImport.update({
  id: '/admin/commission',
  path: '/admin/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProductsIndexRoute = MerchantProductsIndexRouteImport.update({
  id: '/merchant/products/',
  path: '/merchant/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProductsNewRoute = MerchantProductsNewRouteImport.update({
  id: '/merchant/products/new',
  path: '/merchant/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAgentsUserIdRoute = MerchantAgentsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MerchantAgentsRoute,
} as any)
const ApiPublicPayNotifyRoute = ApiPublicPayNotifyRouteImport.update({
  id: '/api/public/pay-notify',
  path: '/api/public/pay-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const PcUsersMerchantMerchantIdRoute =
  PcUsersMerchantMerchantIdRouteImport.update({
    id: '/users_/merchant/$merchantId',
    path: '/users/merchant/$merchantId',
    getParentRoute: () => PcRoute,
  } as any)
const PcUsersBuyerUserIdRoute = PcUsersBuyerUserIdRouteImport.update({
  id: '/users_/buyer/$userId',
  path: '/users/buyer/$userId',
  getParentRoute: () => PcRoute,
} as any)
const PcUsersAgentUserIdRoute = PcUsersAgentUserIdRouteImport.update({
  id: '/users_/agent/$userId',
  path: '/users/agent/$userId',
  getParentRoute: () => PcRoute,
} as any)
const MerchantProductsProductIdIssuesIndexRoute =
  MerchantProductsProductIdIssuesIndexRouteImport.update({
    id: '/merchant/products/$productId/issues/',
    path: '/merchant/products/$productId/issues/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantProductsProductIdIssuesNewRoute =
  MerchantProductsProductIdIssuesNewRouteImport.update({
    id: '/merchant/products/$productId/issues/new',
    path: '/merchant/products/$productId/issues/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantProductsProductIdIssuesBulkImportRoute =
  MerchantProductsProductIdIssuesBulkImportRouteImport.update({
    id: '/merchant/products/$productId/issues/bulk-import',
    path: '/merchant/products/$productId/issues/bulk-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantProductsProductIdIssuesIssueIdEditRoute =
  MerchantProductsProductIdIssuesIssueIdEditRouteImport.update({
    id: '/merchant/products/$productId/issues/$issueId/edit',
    path: '/merchant/products/$productId/issues/$issueId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/merchants': typeof MerchantsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/pc': typeof PcRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/merchant-recruit': typeof AdminMerchantRecruitRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/payment-logs': typeof AdminPaymentLogsRoute
  '/admin/recharge': typeof AdminRechargeRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wechat': typeof AdminWechatRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/agent/invitees': typeof AgentInviteesRoute
  '/agent/merchants': typeof AgentMerchantsRoute
  '/agent/share': typeof AgentShareRoute
  '/apply-agent/$merchantId': typeof ApplyAgentMerchantIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/staff-login': typeof AuthStaffLoginRoute
  '/login/done': typeof LoginDoneRoute
  '/login/iframe-bridge': typeof LoginIframeBridgeRoute
  '/login/wechat-done': typeof LoginWechatDoneRoute
  '/merchant/affiliations': typeof MerchantAffiliationsRoute
  '/merchant/agent-applications': typeof MerchantAgentApplicationsRoute
  '/merchant/agent-recruit': typeof MerchantAgentRecruitRoute
  '/merchant/agents': typeof MerchantAgentsRouteWithChildren
  '/merchant/apply': typeof MerchantApplyRoute
  '/merchant/commission': typeof MerchantCommissionRoute
  '/merchant/messages': typeof MerchantMessagesRoute
  '/merchant/qrcode': typeof MerchantQrcodeRoute
  '/merchant/shop': typeof MerchantShopRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pay/success': typeof PaySuccessRoute
  '/pay/test': typeof PayTestRoute
  '/pc/agents': typeof PcAgentsRoute
  '/pc/commissions': typeof PcCommissionsRoute
  '/pc/customers': typeof PcCustomersRoute
  '/pc/login': typeof PcLoginRoute
  '/pc/orders': typeof PcOrdersRoute
  '/pc/payments': typeof PcPaymentsRoute
  '/pc/users': typeof PcUsersRoute
  '/pc/wallet-transactions': typeof PcWalletTransactionsRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/profile/bind-phone': typeof ProfileBindPhoneRoute
  '/profile/kyc': typeof ProfileKycRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
  '/shop/me': typeof ShopMeRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/pc/': typeof PcIndexRoute
  '/api/public/pay-notify': typeof ApiPublicPayNotifyRoute
  '/merchant/agents/$userId': typeof MerchantAgentsUserIdRoute
  '/merchant/products/new': typeof MerchantProductsNewRoute
  '/merchant/products/': typeof MerchantProductsIndexRoute
  '/pc/users/agent/$userId': typeof PcUsersAgentUserIdRoute
  '/pc/users/buyer/$userId': typeof PcUsersBuyerUserIdRoute
  '/pc/users/merchant/$merchantId': typeof PcUsersMerchantMerchantIdRoute
  '/merchant/products/$productId/issues/bulk-import': typeof MerchantProductsProductIdIssuesBulkImportRoute
  '/merchant/products/$productId/issues/new': typeof MerchantProductsProductIdIssuesNewRoute
  '/merchant/products/$productId/issues/': typeof MerchantProductsProductIdIssuesIndexRoute
  '/merchant/products/$productId/issues/$issueId/edit': typeof MerchantProductsProductIdIssuesIssueIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/merchants': typeof MerchantsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/merchant-recruit': typeof AdminMerchantRecruitRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/payment-logs': typeof AdminPaymentLogsRoute
  '/admin/recharge': typeof AdminRechargeRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wechat': typeof AdminWechatRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/agent/invitees': typeof AgentInviteesRoute
  '/agent/merchants': typeof AgentMerchantsRoute
  '/agent/share': typeof AgentShareRoute
  '/apply-agent/$merchantId': typeof ApplyAgentMerchantIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/staff-login': typeof AuthStaffLoginRoute
  '/login/done': typeof LoginDoneRoute
  '/login/iframe-bridge': typeof LoginIframeBridgeRoute
  '/login/wechat-done': typeof LoginWechatDoneRoute
  '/merchant/affiliations': typeof MerchantAffiliationsRoute
  '/merchant/agent-applications': typeof MerchantAgentApplicationsRoute
  '/merchant/agent-recruit': typeof MerchantAgentRecruitRoute
  '/merchant/agents': typeof MerchantAgentsRouteWithChildren
  '/merchant/apply': typeof MerchantApplyRoute
  '/merchant/commission': typeof MerchantCommissionRoute
  '/merchant/messages': typeof MerchantMessagesRoute
  '/merchant/qrcode': typeof MerchantQrcodeRoute
  '/merchant/shop': typeof MerchantShopRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pay/success': typeof PaySuccessRoute
  '/pay/test': typeof PayTestRoute
  '/pc/agents': typeof PcAgentsRoute
  '/pc/commissions': typeof PcCommissionsRoute
  '/pc/customers': typeof PcCustomersRoute
  '/pc/login': typeof PcLoginRoute
  '/pc/orders': typeof PcOrdersRoute
  '/pc/payments': typeof PcPaymentsRoute
  '/pc/users': typeof PcUsersRoute
  '/pc/wallet-transactions': typeof PcWalletTransactionsRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/profile/bind-phone': typeof ProfileBindPhoneRoute
  '/profile/kyc': typeof ProfileKycRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
  '/shop/me': typeof ShopMeRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/pc': typeof PcIndexRoute
  '/api/public/pay-notify': typeof ApiPublicPayNotifyRoute
  '/merchant/agents/$userId': typeof MerchantAgentsUserIdRoute
  '/merchant/products/new': typeof MerchantProductsNewRoute
  '/merchant/products': typeof MerchantProductsIndexRoute
  '/pc/users/agent/$userId': typeof PcUsersAgentUserIdRoute
  '/pc/users/buyer/$userId': typeof PcUsersBuyerUserIdRoute
  '/pc/users/merchant/$merchantId': typeof PcUsersMerchantMerchantIdRoute
  '/merchant/products/$productId/issues/bulk-import': typeof MerchantProductsProductIdIssuesBulkImportRoute
  '/merchant/products/$productId/issues/new': typeof MerchantProductsProductIdIssuesNewRoute
  '/merchant/products/$productId/issues': typeof MerchantProductsProductIdIssuesIndexRoute
  '/merchant/products/$productId/issues/$issueId/edit': typeof MerchantProductsProductIdIssuesIssueIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/merchants': typeof MerchantsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/pc': typeof PcRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/commission': typeof AdminCommissionRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/merchant-recruit': typeof AdminMerchantRecruitRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/payment-logs': typeof AdminPaymentLogsRoute
  '/admin/recharge': typeof AdminRechargeRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wechat': typeof AdminWechatRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/agent_/invitees': typeof AgentInviteesRoute
  '/agent_/merchants': typeof AgentMerchantsRoute
  '/agent_/share': typeof AgentShareRoute
  '/apply-agent/$merchantId': typeof ApplyAgentMerchantIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/staff-login': typeof AuthStaffLoginRoute
  '/login/done': typeof LoginDoneRoute
  '/login/iframe-bridge': typeof LoginIframeBridgeRoute
  '/login/wechat-done': typeof LoginWechatDoneRoute
  '/merchant/affiliations': typeof MerchantAffiliationsRoute
  '/merchant/agent-applications': typeof MerchantAgentApplicationsRoute
  '/merchant/agent-recruit': typeof MerchantAgentRecruitRoute
  '/merchant/agents': typeof MerchantAgentsRouteWithChildren
  '/merchant/apply': typeof MerchantApplyRoute
  '/merchant/commission': typeof MerchantCommissionRoute
  '/merchant/messages': typeof MerchantMessagesRoute
  '/merchant/qrcode': typeof MerchantQrcodeRoute
  '/merchant/shop': typeof MerchantShopRoute
  '/orders_/$orderId': typeof OrdersOrderIdRoute
  '/pay/success': typeof PaySuccessRoute
  '/pay/test': typeof PayTestRoute
  '/pc/agents': typeof PcAgentsRoute
  '/pc/commissions': typeof PcCommissionsRoute
  '/pc/customers': typeof PcCustomersRoute
  '/pc/login': typeof PcLoginRoute
  '/pc/orders': typeof PcOrdersRoute
  '/pc/payments': typeof PcPaymentsRoute
  '/pc/users': typeof PcUsersRoute
  '/pc/wallet-transactions': typeof PcWalletTransactionsRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/profile_/bind-phone': typeof ProfileBindPhoneRoute
  '/profile_/kyc': typeof ProfileKycRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
  '/shop/me': typeof ShopMeRoute
  '/wallet_/transactions': typeof WalletTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/pc/': typeof PcIndexRoute
  '/api/public/pay-notify': typeof ApiPublicPayNotifyRoute
  '/merchant/agents/$userId': typeof MerchantAgentsUserIdRoute
  '/merchant/products/new': typeof MerchantProductsNewRoute
  '/merchant/products/': typeof MerchantProductsIndexRoute
  '/pc/users_/agent/$userId': typeof PcUsersAgentUserIdRoute
  '/pc/users_/buyer/$userId': typeof PcUsersBuyerUserIdRoute
  '/pc/users_/merchant/$merchantId': typeof PcUsersMerchantMerchantIdRoute
  '/merchant/products/$productId/issues/bulk-import': typeof MerchantProductsProductIdIssuesBulkImportRoute
  '/merchant/products/$productId/issues/new': typeof MerchantProductsProductIdIssuesNewRoute
  '/merchant/products/$productId/issues/': typeof MerchantProductsProductIdIssuesIndexRoute
  '/merchant/products/$productId/issues/$issueId/edit': typeof MerchantProductsProductIdIssuesIssueIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/apply'
    | '/contact'
    | '/feedback'
    | '/merchants'
    | '/messages'
    | '/orders'
    | '/pc'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/wallet'
    | '/admin/agents'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/commission'
    | '/admin/kyc'
    | '/admin/merchant-recruit'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/payment'
    | '/admin/payment-logs'
    | '/admin/recharge'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wechat'
    | '/admin/withdrawals'
    | '/agent/invitees'
    | '/agent/merchants'
    | '/agent/share'
    | '/apply-agent/$merchantId'
    | '/auth/login'
    | '/auth/staff-login'
    | '/login/done'
    | '/login/iframe-bridge'
    | '/login/wechat-done'
    | '/merchant/affiliations'
    | '/merchant/agent-applications'
    | '/merchant/agent-recruit'
    | '/merchant/agents'
    | '/merchant/apply'
    | '/merchant/commission'
    | '/merchant/messages'
    | '/merchant/qrcode'
    | '/merchant/shop'
    | '/orders/$orderId'
    | '/pay/success'
    | '/pay/test'
    | '/pc/agents'
    | '/pc/commissions'
    | '/pc/customers'
    | '/pc/login'
    | '/pc/orders'
    | '/pc/payments'
    | '/pc/users'
    | '/pc/wallet-transactions'
    | '/product/$productId'
    | '/profile/bind-phone'
    | '/profile/kyc'
    | '/shop/$merchantId'
    | '/shop/me'
    | '/wallet/transactions'
    | '/admin/'
    | '/merchant/'
    | '/pc/'
    | '/api/public/pay-notify'
    | '/merchant/agents/$userId'
    | '/merchant/products/new'
    | '/merchant/products/'
    | '/pc/users/agent/$userId'
    | '/pc/users/buyer/$userId'
    | '/pc/users/merchant/$merchantId'
    | '/merchant/products/$productId/issues/bulk-import'
    | '/merchant/products/$productId/issues/new'
    | '/merchant/products/$productId/issues/'
    | '/merchant/products/$productId/issues/$issueId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/apply'
    | '/contact'
    | '/feedback'
    | '/merchants'
    | '/messages'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/wallet'
    | '/admin/agents'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/commission'
    | '/admin/kyc'
    | '/admin/merchant-recruit'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/payment'
    | '/admin/payment-logs'
    | '/admin/recharge'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wechat'
    | '/admin/withdrawals'
    | '/agent/invitees'
    | '/agent/merchants'
    | '/agent/share'
    | '/apply-agent/$merchantId'
    | '/auth/login'
    | '/auth/staff-login'
    | '/login/done'
    | '/login/iframe-bridge'
    | '/login/wechat-done'
    | '/merchant/affiliations'
    | '/merchant/agent-applications'
    | '/merchant/agent-recruit'
    | '/merchant/agents'
    | '/merchant/apply'
    | '/merchant/commission'
    | '/merchant/messages'
    | '/merchant/qrcode'
    | '/merchant/shop'
    | '/orders/$orderId'
    | '/pay/success'
    | '/pay/test'
    | '/pc/agents'
    | '/pc/commissions'
    | '/pc/customers'
    | '/pc/login'
    | '/pc/orders'
    | '/pc/payments'
    | '/pc/users'
    | '/pc/wallet-transactions'
    | '/product/$productId'
    | '/profile/bind-phone'
    | '/profile/kyc'
    | '/shop/$merchantId'
    | '/shop/me'
    | '/wallet/transactions'
    | '/admin'
    | '/merchant'
    | '/pc'
    | '/api/public/pay-notify'
    | '/merchant/agents/$userId'
    | '/merchant/products/new'
    | '/merchant/products'
    | '/pc/users/agent/$userId'
    | '/pc/users/buyer/$userId'
    | '/pc/users/merchant/$merchantId'
    | '/merchant/products/$productId/issues/bulk-import'
    | '/merchant/products/$productId/issues/new'
    | '/merchant/products/$productId/issues'
    | '/merchant/products/$productId/issues/$issueId/edit'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/apply'
    | '/contact'
    | '/feedback'
    | '/merchants'
    | '/messages'
    | '/orders'
    | '/pc'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/wallet'
    | '/admin/agents'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/commission'
    | '/admin/kyc'
    | '/admin/merchant-recruit'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/payment'
    | '/admin/payment-logs'
    | '/admin/recharge'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wechat'
    | '/admin/withdrawals'
    | '/agent_/invitees'
    | '/agent_/merchants'
    | '/agent_/share'
    | '/apply-agent/$merchantId'
    | '/auth/login'
    | '/auth/staff-login'
    | '/login/done'
    | '/login/iframe-bridge'
    | '/login/wechat-done'
    | '/merchant/affiliations'
    | '/merchant/agent-applications'
    | '/merchant/agent-recruit'
    | '/merchant/agents'
    | '/merchant/apply'
    | '/merchant/commission'
    | '/merchant/messages'
    | '/merchant/qrcode'
    | '/merchant/shop'
    | '/orders_/$orderId'
    | '/pay/success'
    | '/pay/test'
    | '/pc/agents'
    | '/pc/commissions'
    | '/pc/customers'
    | '/pc/login'
    | '/pc/orders'
    | '/pc/payments'
    | '/pc/users'
    | '/pc/wallet-transactions'
    | '/product/$productId'
    | '/profile_/bind-phone'
    | '/profile_/kyc'
    | '/shop/$merchantId'
    | '/shop/me'
    | '/wallet_/transactions'
    | '/admin/'
    | '/merchant/'
    | '/pc/'
    | '/api/public/pay-notify'
    | '/merchant/agents/$userId'
    | '/merchant/products/new'
    | '/merchant/products/'
    | '/pc/users_/agent/$userId'
    | '/pc/users_/buyer/$userId'
    | '/pc/users_/merchant/$merchantId'
    | '/merchant/products/$productId/issues/bulk-import'
    | '/merchant/products/$productId/issues/new'
    | '/merchant/products/$productId/issues/'
    | '/merchant/products/$productId/issues/$issueId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  FeedbackRoute: typeof FeedbackRoute
  MerchantsRoute: typeof MerchantsRoute
  MessagesRoute: typeof MessagesRoute
  OrdersRoute: typeof OrdersRoute
  PcRoute: typeof PcRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCommissionRoute: typeof AdminCommissionRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminMerchantRecruitRoute: typeof AdminMerchantRecruitRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentRoute: typeof AdminPaymentRoute
  AdminPaymentLogsRoute: typeof AdminPaymentLogsRoute
  AdminRechargeRoute: typeof AdminRechargeRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWechatRoute: typeof AdminWechatRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AgentInviteesRoute: typeof AgentInviteesRoute
  AgentMerchantsRoute: typeof AgentMerchantsRoute
  AgentShareRoute: typeof AgentShareRoute
  ApplyAgentMerchantIdRoute: typeof ApplyAgentMerchantIdRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthStaffLoginRoute: typeof AuthStaffLoginRoute
  LoginDoneRoute: typeof LoginDoneRoute
  LoginIframeBridgeRoute: typeof LoginIframeBridgeRoute
  LoginWechatDoneRoute: typeof LoginWechatDoneRoute
  MerchantAffiliationsRoute: typeof MerchantAffiliationsRoute
  MerchantAgentApplicationsRoute: typeof MerchantAgentApplicationsRoute
  MerchantAgentRecruitRoute: typeof MerchantAgentRecruitRoute
  MerchantAgentsRoute: typeof MerchantAgentsRouteWithChildren
  MerchantApplyRoute: typeof MerchantApplyRoute
  MerchantCommissionRoute: typeof MerchantCommissionRoute
  MerchantMessagesRoute: typeof MerchantMessagesRoute
  MerchantQrcodeRoute: typeof MerchantQrcodeRoute
  MerchantShopRoute: typeof MerchantShopRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PaySuccessRoute: typeof PaySuccessRoute
  PayTestRoute: typeof PayTestRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ProfileBindPhoneRoute: typeof ProfileBindPhoneRoute
  ProfileKycRoute: typeof ProfileKycRoute
  ShopMerchantIdRoute: typeof ShopMerchantIdRoute
  ShopMeRoute: typeof ShopMeRoute
  WalletTransactionsRoute: typeof WalletTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  ApiPublicPayNotifyRoute: typeof ApiPublicPayNotifyRoute
  MerchantProductsNewRoute: typeof MerchantProductsNewRoute
  MerchantProductsIndexRoute: typeof MerchantProductsIndexRoute
  MerchantProductsProductIdIssuesBulkImportRoute: typeof MerchantProductsProductIdIssuesBulkImportRoute
  MerchantProductsProductIdIssuesNewRoute: typeof MerchantProductsProductIdIssuesNewRoute
  MerchantProductsProductIdIssuesIndexRoute: typeof MerchantProductsProductIdIssuesIndexRoute
  MerchantProductsProductIdIssuesIssueIdEditRoute: typeof MerchantProductsProductIdIssuesIssueIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc': {
      id: '/pc'
      path: '/pc'
      fullPath: '/pc'
      preLoaderRoute: typeof PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/': {
      id: '/pc/'
      path: '/'
      fullPath: '/pc/'
      preLoaderRoute: typeof PcIndexRouteImport
      parentRoute: typeof PcRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet_/transactions': {
      id: '/wallet_/transactions'
      path: '/wallet/transactions'
      fullPath: '/wallet/transactions'
      preLoaderRoute: typeof WalletTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/me': {
      id: '/shop/me'
      path: '/shop/me'
      fullPath: '/shop/me'
      preLoaderRoute: typeof ShopMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$merchantId': {
      id: '/shop/$merchantId'
      path: '/shop/$merchantId'
      fullPath: '/shop/$merchantId'
      preLoaderRoute: typeof ShopMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/kyc': {
      id: '/profile_/kyc'
      path: '/profile/kyc'
      fullPath: '/profile/kyc'
      preLoaderRoute: typeof ProfileKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/bind-phone': {
      id: '/profile_/bind-phone'
      path: '/profile/bind-phone'
      fullPath: '/profile/bind-phone'
      preLoaderRoute: typeof ProfileBindPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/wallet-transactions': {
      id: '/pc/wallet-transactions'
      path: '/wallet-transactions'
      fullPath: '/pc/wallet-transactions'
      preLoaderRoute: typeof PcWalletTransactionsRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/users': {
      id: '/pc/users'
      path: '/users'
      fullPath: '/pc/users'
      preLoaderRoute: typeof PcUsersRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/payments': {
      id: '/pc/payments'
      path: '/payments'
      fullPath: '/pc/payments'
      preLoaderRoute: typeof PcPaymentsRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/orders': {
      id: '/pc/orders'
      path: '/orders'
      fullPath: '/pc/orders'
      preLoaderRoute: typeof PcOrdersRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/login': {
      id: '/pc/login'
      path: '/login'
      fullPath: '/pc/login'
      preLoaderRoute: typeof PcLoginRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/customers': {
      id: '/pc/customers'
      path: '/customers'
      fullPath: '/pc/customers'
      preLoaderRoute: typeof PcCustomersRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/commissions': {
      id: '/pc/commissions'
      path: '/commissions'
      fullPath: '/pc/commissions'
      preLoaderRoute: typeof PcCommissionsRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/agents': {
      id: '/pc/agents'
      path: '/agents'
      fullPath: '/pc/agents'
      preLoaderRoute: typeof PcAgentsRouteImport
      parentRoute: typeof PcRoute
    }
    '/pay/test': {
      id: '/pay/test'
      path: '/pay/test'
      fullPath: '/pay/test'
      preLoaderRoute: typeof PayTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/pay/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$orderId': {
      id: '/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/shop': {
      id: '/merchant/shop'
      path: '/merchant/shop'
      fullPath: '/merchant/shop'
      preLoaderRoute: typeof MerchantShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/qrcode': {
      id: '/merchant/qrcode'
      path: '/merchant/qrcode'
      fullPath: '/merchant/qrcode'
      preLoaderRoute: typeof MerchantQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/messages': {
      id: '/merchant/messages'
      path: '/merchant/messages'
      fullPath: '/merchant/messages'
      preLoaderRoute: typeof MerchantMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/commission': {
      id: '/merchant/commission'
      path: '/merchant/commission'
      fullPath: '/merchant/commission'
      preLoaderRoute: typeof MerchantCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/apply': {
      id: '/merchant/apply'
      path: '/merchant/apply'
      fullPath: '/merchant/apply'
      preLoaderRoute: typeof MerchantApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/agents': {
      id: '/merchant/agents'
      path: '/merchant/agents'
      fullPath: '/merchant/agents'
      preLoaderRoute: typeof MerchantAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/agent-recruit': {
      id: '/merchant/agent-recruit'
      path: '/merchant/agent-recruit'
      fullPath: '/merchant/agent-recruit'
      preLoaderRoute: typeof MerchantAgentRecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/agent-applications': {
      id: '/merchant/agent-applications'
      path: '/merchant/agent-applications'
      fullPath: '/merchant/agent-applications'
      preLoaderRoute: typeof MerchantAgentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/affiliations': {
      id: '/merchant/affiliations'
      path: '/merchant/affiliations'
      fullPath: '/merchant/affiliations'
      preLoaderRoute: typeof MerchantAffiliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/wechat-done': {
      id: '/login/wechat-done'
      path: '/login/wechat-done'
      fullPath: '/login/wechat-done'
      preLoaderRoute: typeof LoginWechatDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/iframe-bridge': {
      id: '/login/iframe-bridge'
      path: '/login/iframe-bridge'
      fullPath: '/login/iframe-bridge'
      preLoaderRoute: typeof LoginIframeBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/done': {
      id: '/login/done'
      path: '/login/done'
      fullPath: '/login/done'
      preLoaderRoute: typeof LoginDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/staff-login': {
      id: '/auth/staff-login'
      path: '/auth/staff-login'
      fullPath: '/auth/staff-login'
      preLoaderRoute: typeof AuthStaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-agent/$merchantId': {
      id: '/apply-agent/$merchantId'
      path: '/apply-agent/$merchantId'
      fullPath: '/apply-agent/$merchantId'
      preLoaderRoute: typeof ApplyAgentMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent_/share': {
      id: '/agent_/share'
      path: '/agent/share'
      fullPath: '/agent/share'
      preLoaderRoute: typeof AgentShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent_/merchants': {
      id: '/agent_/merchants'
      path: '/agent/merchants'
      fullPath: '/agent/merchants'
      preLoaderRoute: typeof AgentMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent_/invitees': {
      id: '/agent_/invitees'
      path: '/agent/invitees'
      fullPath: '/agent/invitees'
      preLoaderRoute: typeof AgentInviteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wechat': {
      id: '/admin/wechat'
      path: '/admin/wechat'
      fullPath: '/admin/wechat'
      preLoaderRoute: typeof AdminWechatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recharge': {
      id: '/admin/recharge'
      path: '/admin/recharge'
      fullPath: '/admin/recharge'
      preLoaderRoute: typeof AdminRechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-logs': {
      id: '/admin/payment-logs'
      path: '/admin/payment-logs'
      fullPath: '/admin/payment-logs'
      preLoaderRoute: typeof AdminPaymentLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment': {
      id: '/admin/payment'
      path: '/admin/payment'
      fullPath: '/admin/payment'
      preLoaderRoute: typeof AdminPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchant-recruit': {
      id: '/admin/merchant-recruit'
      path: '/admin/merchant-recruit'
      fullPath: '/admin/merchant-recruit'
      preLoaderRoute: typeof AdminMerchantRecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commission': {
      id: '/admin/commission'
      path: '/admin/commission'
      fullPath: '/admin/commission'
      preLoaderRoute: typeof AdminCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/products/': {
      id: '/merchant/products/'
      path: '/merchant/products'
      fullPath: '/merchant/products/'
      preLoaderRoute: typeof MerchantProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/products/new': {
      id: '/merchant/products/new'
      path: '/merchant/products/new'
      fullPath: '/merchant/products/new'
      preLoaderRoute: typeof MerchantProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/agents/$userId': {
      id: '/merchant/agents/$userId'
      path: '/$userId'
      fullPath: '/merchant/agents/$userId'
      preLoaderRoute: typeof MerchantAgentsUserIdRouteImport
      parentRoute: typeof MerchantAgentsRoute
    }
    '/api/public/pay-notify': {
      id: '/api/public/pay-notify'
      path: '/api/public/pay-notify'
      fullPath: '/api/public/pay-notify'
      preLoaderRoute: typeof ApiPublicPayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/users_/merchant/$merchantId': {
      id: '/pc/users_/merchant/$merchantId'
      path: '/users/merchant/$merchantId'
      fullPath: '/pc/users/merchant/$merchantId'
      preLoaderRoute: typeof PcUsersMerchantMerchantIdRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/users_/buyer/$userId': {
      id: '/pc/users_/buyer/$userId'
      path: '/users/buyer/$userId'
      fullPath: '/pc/users/buyer/$userId'
      preLoaderRoute: typeof PcUsersBuyerUserIdRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/users_/agent/$userId': {
      id: '/pc/users_/agent/$userId'
      path: '/users/agent/$userId'
      fullPath: '/pc/users/agent/$userId'
      preLoaderRoute: typeof PcUsersAgentUserIdRouteImport
      parentRoute: typeof PcRoute
    }
    '/merchant/products/$productId/issues/': {
      id: '/merchant/products/$productId/issues/'
      path: '/merchant/products/$productId/issues'
      fullPath: '/merchant/products/$productId/issues/'
      preLoaderRoute: typeof MerchantProductsProductIdIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/products/$productId/issues/new': {
      id: '/merchant/products/$productId/issues/new'
      path: '/merchant/products/$productId/issues/new'
      fullPath: '/merchant/products/$productId/issues/new'
      preLoaderRoute: typeof MerchantProductsProductIdIssuesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/products/$productId/issues/bulk-import': {
      id: '/merchant/products/$productId/issues/bulk-import'
      path: '/merchant/products/$productId/issues/bulk-import'
      fullPath: '/merchant/products/$productId/issues/bulk-import'
      preLoaderRoute: typeof MerchantProductsProductIdIssuesBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/products/$productId/issues/$issueId/edit': {
      id: '/merchant/products/$productId/issues/$issueId/edit'
      path: '/merchant/products/$productId/issues/$issueId/edit'
      fullPath: '/merchant/products/$productId/issues/$issueId/edit'
      preLoaderRoute: typeof MerchantProductsProductIdIssuesIssueIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PcRouteChildren {
  PcAgentsRoute: typeof PcAgentsRoute
  PcCommissionsRoute: typeof PcCommissionsRoute
  PcCustomersRoute: typeof PcCustomersRoute
  PcLoginRoute: typeof PcLoginRoute
  PcOrdersRoute: typeof PcOrdersRoute
  PcPaymentsRoute: typeof PcPaymentsRoute
  PcUsersRoute: typeof PcUsersRoute
  PcWalletTransactionsRoute: typeof PcWalletTransactionsRoute
  PcIndexRoute: typeof PcIndexRoute
  PcUsersAgentUserIdRoute: typeof PcUsersAgentUserIdRoute
  PcUsersBuyerUserIdRoute: typeof PcUsersBuyerUserIdRoute
  PcUsersMerchantMerchantIdRoute: typeof PcUsersMerchantMerchantIdRoute
}

const PcRouteChildren: PcRouteChildren = {
  PcAgentsRoute: PcAgentsRoute,
  PcCommissionsRoute: PcCommissionsRoute,
  PcCustomersRoute: PcCustomersRoute,
  PcLoginRoute: PcLoginRoute,
  PcOrdersRoute: PcOrdersRoute,
  PcPaymentsRoute: PcPaymentsRoute,
  PcUsersRoute: PcUsersRoute,
  PcWalletTransactionsRoute: PcWalletTransactionsRoute,
  PcIndexRoute: PcIndexRoute,
  PcUsersAgentUserIdRoute: PcUsersAgentUserIdRoute,
  PcUsersBuyerUserIdRoute: PcUsersBuyerUserIdRoute,
  PcUsersMerchantMerchantIdRoute: PcUsersMerchantMerchantIdRoute,
}

const PcRouteWithChildren = PcRoute._addFileChildren(PcRouteChildren)

interface MerchantAgentsRouteChildren {
  MerchantAgentsUserIdRoute: typeof MerchantAgentsUserIdRoute
}

const MerchantAgentsRouteChildren: MerchantAgentsRouteChildren = {
  MerchantAgentsUserIdRoute: MerchantAgentsUserIdRoute,
}

const MerchantAgentsRouteWithChildren = MerchantAgentsRoute._addFileChildren(
  MerchantAgentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  FeedbackRoute: FeedbackRoute,
  MerchantsRoute: MerchantsRoute,
  MessagesRoute: MessagesRoute,
  OrdersRoute: OrdersRoute,
  PcRoute: PcRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCommissionRoute: AdminCommissionRoute,
  AdminKycRoute: AdminKycRoute,
  AdminMerchantRecruitRoute: AdminMerchantRecruitRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentRoute: AdminPaymentRoute,
  AdminPaymentLogsRoute: AdminPaymentLogsRoute,
  AdminRechargeRoute: AdminRechargeRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWechatRoute: AdminWechatRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AgentInviteesRoute: AgentInviteesRoute,
  AgentMerchantsRoute: AgentMerchantsRoute,
  AgentShareRoute: AgentShareRoute,
  ApplyAgentMerchantIdRoute: ApplyAgentMerchantIdRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthStaffLoginRoute: AuthStaffLoginRoute,
  LoginDoneRoute: LoginDoneRoute,
  LoginIframeBridgeRoute: LoginIframeBridgeRoute,
  LoginWechatDoneRoute: LoginWechatDoneRoute,
  MerchantAffiliationsRoute: MerchantAffiliationsRoute,
  MerchantAgentApplicationsRoute: MerchantAgentApplicationsRoute,
  MerchantAgentRecruitRoute: MerchantAgentRecruitRoute,
  MerchantAgentsRoute: MerchantAgentsRouteWithChildren,
  MerchantApplyRoute: MerchantApplyRoute,
  MerchantCommissionRoute: MerchantCommissionRoute,
  MerchantMessagesRoute: MerchantMessagesRoute,
  MerchantQrcodeRoute: MerchantQrcodeRoute,
  MerchantShopRoute: MerchantShopRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PaySuccessRoute: PaySuccessRoute,
  PayTestRoute: PayTestRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ProfileBindPhoneRoute: ProfileBindPhoneRoute,
  ProfileKycRoute: ProfileKycRoute,
  ShopMerchantIdRoute: ShopMerchantIdRoute,
  ShopMeRoute: ShopMeRoute,
  WalletTransactionsRoute: WalletTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  ApiPublicPayNotifyRoute: ApiPublicPayNotifyRoute,
  MerchantProductsNewRoute: MerchantProductsNewRoute,
  MerchantProductsIndexRoute: MerchantProductsIndexRoute,
  MerchantProductsProductIdIssuesBulkImportRoute:
    MerchantProductsProductIdIssuesBulkImportRoute,
  MerchantProductsProductIdIssuesNewRoute:
    MerchantProductsProductIdIssuesNewRoute,
  MerchantProductsProductIdIssuesIndexRoute:
    MerchantProductsProductIdIssuesIndexRoute,
  MerchantProductsProductIdIssuesIssueIdEditRoute:
    MerchantProductsProductIdIssuesIssueIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
