/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopMerchantIdRouteImport } from './routes/shop.$merchantId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMerchantIdRoute = ShopMerchantIdRouteImport.update({
  id: '/shop/$merchantId',
  path: '/shop/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$merchantId': typeof ShopMerchantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/product/$productId' | '/shop/$merchantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/product/$productId' | '/shop/$merchantId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/product/$productId'
    | '/shop/$merchantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ShopMerchantIdRoute: typeof ShopMerchantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$merchantId': {
      id: '/shop/$merchantId'
      path: '/shop/$merchantId'
      fullPath: '/shop/$merchantId'
      preLoaderRoute: typeof ShopMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ShopMerchantIdRoute: ShopMerchantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
